Remove DB backups older than 7 days automatically

diff --git a/docker/db-backup/scripts/auto_backup b/docker/db-backup/scripts/auto_backup
--- a/docker/db-backup/scripts/auto_backup
+++ b/docker/db-backup/scripts/auto_backup
@@ -9,8 +9,11 @@ while true; do
 
   if [[ $? == 0 ]]; then
     echo "$(date +'%F %T.%3N') Backup completed successfully."
+
+    echo "$(date +'%F %T.%3N') Removing backups older than 7 days..."
+    find "/backup" -maxdepth 1 -type d -mtime +7 -exec rm -rf {} +
   else
-    echo "$(date +'%F %T.%3N') ERROR: Backup failed!" >&2
+    echo "$(date +'%F %T.%3N') ERROR: Backup failed! Cleanup is skipped." >&2
   fi
 
   echo "$(date +'%F %T.%3N') Sleeping for 1 hour..."
